[build]
base    = "frontend"
publish = "build"
command = "CI= npm run build"

[[redirects]]
  from = "/api/*"
  to   = "https://a7d73eceeb73.ngrok-free.app/:splat"
  status = 200
  force  = true

# Map pretty API paths to functions
[[redirects]]
  from = "/api/auth/turnstile-verify"
  to = "/.netlify/functions/turnstile-verify"
  status = 200

[[redirects]]
  from = "/api/auth/check"
  to = "/.netlify/functions/auth-check"
  status = 200